---
- name: Deploy RHEL machine
  hosts: all
  become: true

  tasks:
  - name: Install necessary packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - wget
      - net-tools

  - name: Configure firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    with_items:
      - ssh
      - http
      - https

  - name: Configure SELinux
    selinux:
      policy: targeted
      state: permissive

  - name: Update system
    yum:
      name: '*'
      state: latest
      exclude: kernel*

  - name: Reboot the system
    reboot:
      reboot_timeout: 300
      post_reboot_delay: 30
      test_command: /sbin/init

  - name: Install additional packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - epel-release
      - gcc
      - make
      - python3-pip
